
-- +goose Up
ALTER TABLE School
  ALTER COLUMN CreatedAt SET DEFAULT 'now()';

ALTER TABLE Application
  ALTER COLUMN CreatedAt SET DEFAULT 'now()';

ALTER TABLE Users
  ALTER COLUMN CreatedAt SET DEFAULT 'now()';


-- +goose Down
ALTER TABLE School
  ALTER COLUMN CreatedAt DROP DEFAULT;

ALTER TABLE Application
  ALTER COLUMN CreatedAt DROP DEFAULT;

ALTER TABLE Users
  ALTER COLUMN CreatedAt DROP DEFAULT;
