source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'rails', '4.2.7.1'
gem 'sass-rails', '~> 4.0.5'
gem 'uglifier', '>= 2.7.2'
gem 'coffee-rails', '~> 4.0.1'
gem 'therubyracer'
gem 'haml-rails', '>= 1.0.0'
gem 'redcarpet', '>= 3.2.3'
gem 'rack-ssl-enforcer'
gem 'rack-attack', '>= 4.3.1'
gem 'unf_ext'

gem 'jquery-rails', '>= 3.1.3'
gem 'jbuilder', '~> 2.2', '>= 2.2.5'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'foundation-rails', '>= 5.4.5.0'
gem 'sentry-raven'
gem 'rails-assets-Hover'
gem 'rails-assets-underscore'
gem 'gmaps4rails'
gem 'simple_form', '>= 3.1.0'
gem 'enum_help'
gem 'pluggable_js', '>= 2.0.4'
gem 'figaro'
gem 'validates_email_format_of'
gem 'stripe'
gem 'faraday'
gem 'rack-reverse-proxy', require: 'rack/reverse_proxy'

group :development, :test do
  gem 'sqlite3'
  gem 'spring'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
  gem 'byebug'

  gem 'rspec-rails', '>= 3.1.0'
  gem 'guard-rspec'
  gem 'shoulda', '>= 3.5.0'
  gem 'factory_girl_rails', '>= 4.5.0'
  gem 'capybara', '>= 2.4.4'
  gem 'faker'
  gem 'email_spec', '>= 1.6.0'
  gem 'rspec_junit_formatter'
end

group :production do
  gem 'puma'
  gem 'rack-timeout'
  gem 'pg'
  gem 'rails_12factor'
end
