source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'rails', '4.1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer'
gem 'haml-rails'
gem 'redcarpet'
gem 'rack-ssl-enforcer'
gem 'rack-attack'
gem 'unf_ext'

gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'foundation-rails'
gem 'sentry-raven'
gem 'rails-assets-Hover'
gem 'rails-assets-underscore'
gem 'gmaps4rails'
gem 'simple_form'
gem 'enum_help'
gem 'pluggable_js'
gem 'figaro'
gem 'validates_email_format_of'
gem 'stripe'
gem 'faraday'
gem 'rack-reverse-proxy', require: 'rack/reverse_proxy'

group :development, :test do
  gem 'sqlite3'
  gem 'spring'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
  gem 'byebug'

  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'shoulda'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'faker'
  gem 'email_spec'
  gem 'rspec_junit_formatter'
end

group :production do
  gem 'puma'
  gem 'rack-timeout'
  gem 'pg'
  gem 'rails_12factor'
end
